#springboot 内置属性
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html

# 服务器的端口
server:
  port: 80


spring:
  # 修改banner
  banner:
    image:
      location: logo.png
  # 数据库相关配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root

# 日志的级别
logging:
  level:
    root: info

# MybatisPlus的配置
mybatis-plus:
#  global-config:
#    db-config:
      # 前缀
#      table-prefix: tb_
      # id自增长
#      id-type: auto
  # 打印日志(测试时候用)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
